import type { SpinRecord } from '@lucky/shared-types';

export const SPIN_HISTORY_HEADERS = [
  'session_id',
  'session_seed',
  'spin_number',
  'spin_index',
  'timestamp',
  'configuration_id',
  'configuration_version',
  'profile_name',
  'bet',
  'base_win',
  'feature_win',
  'base_regular_win',
  'base_scatter_win',
  'base_multiplier_uplift',
  'feature_regular_win',
  'feature_scatter_win',
  'feature_multiplier_uplift',
  'total_win',
  'win_multiple',
  'winning',
  'winning_outcomes',
  'total_tumble_rounds',
  'total_tumble_triggers',
  'base_tumble_rounds',
  'free_game_tumble_rounds',
  'free_game_tumble_triggers',
  'maximum_tumble_depth',
  'maximum_base_tumble_depth',
  'maximum_free_game_tumble_depth',
  'bathala_activations',
  'bathala_symbols_removed',
  'bathala_next_win_conversions',
  'multiplier_appeared',
  'multiplier_values',
  'summed_multiplier',
  'multiplied_tumble_rounds',
  'summed_effective_multipliers',
  'scatter_count',
  'feature_triggered',
  'free_games_awarded',
  'free_games_played',
  'retrigger_count',
  'ending_free_game_multiplier',
  'maximum_win_applied',
] as const;

function cell(value: string | number | boolean | undefined): string {
  const text = value === undefined ? '' : String(value);
  return /[",\r\n]/u.test(text) ? `"${text.replaceAll('"', '""')}"` : text;
}

export function serializeSpinHistoryCsv(records: readonly SpinRecord[]): string {
  const rows = records.map((record) => [
    record.sessionId,
    record.sessionSeed,
    record.spinNumber,
    record.spinIndex,
    record.timestamp,
    record.configurationId,
    record.configurationVersion,
    record.profileName,
    record.bet,
    record.baseWin,
    record.featureWin,
    record.baseRegularWin,
    record.baseScatterWin,
    record.baseMultiplierUplift,
    record.featureRegularWin,
    record.featureScatterWin,
    record.featureMultiplierUplift,
    record.totalWin,
    record.winMultiple,
    record.winning,
    JSON.stringify(record.winOutcomes),
    record.totalTumbleRounds,
    record.totalTumbleTriggers,
    record.baseTumbleRounds,
    record.freeGameTumbleRounds,
    record.freeGameTumbleTriggers,
    record.maximumTumbleDepth,
    record.maximumBaseTumbleDepth,
    record.maximumFreeGameTumbleDepth,
    record.bathalaActivations,
    record.bathalaSymbolsRemoved,
    record.bathalaNextWinConversions,
    record.multiplierAppeared,
    record.multiplierValues.join('|'),
    record.summedMultiplier,
    record.multipliedTumbleRounds,
    record.summedEffectiveMultipliers,
    record.scatterCount,
    record.featureTriggered,
    record.freeGamesAwarded,
    record.freeGamesPlayed,
    record.retriggerCount,
    record.endingFreeGameMultiplier,
    record.maximumWinApplied,
  ]);
  return `${SPIN_HISTORY_HEADERS.join(',')}\r\n${rows.map((row) => row.map(cell).join(',')).join('\r\n')}\r\n`;
}

const safe = (value: string): string => value.replace(/[^a-z0-9._-]+/giu, '-');
export function spinHistoryFilename(configurationId: string, sessionId: string): string {
  return `lucky888-spin-history_${safe(configurationId)}_${safe(sessionId)}.csv`;
}
