import type { RuntimeGameConfig } from '@lucky/shared-types';

export function fixtureConfig(): RuntimeGameConfig {
  return {
    schemaVersion: '1.0.0',
    gameId: 'lucky888',
    gameName: 'LUCKY888',
    gameVersion: '1.0.0',
    configurationId: 'fixture-v1',
    selectedRtpProfile: 'fixture-v1',
    payModel: 'fixed-paylines-left-to-right',
    reelCount: 3,
    visibleRows: 1,
    lineBetCredits: 1,
    totalBetCredits: 1,
    maximumWinCredits: 50,
    maximumWinScope: 'paid-spin-including-feature',
    symbols: [
      { id: 'A', name: 'A', category: 'regular', display: 'A' },
      { id: 'B', name: 'B', category: 'regular', display: 'B' },
      { id: 'W', name: 'Wild', category: 'wild', display: 'W' },
      { id: 'S', name: 'Scatter', category: 'scatter', display: 'S' },
    ],
    reelStrips: [
      ['A', 'B', 'S'],
      ['A', 'B', 'S'],
      ['A', 'B', 'S'],
    ],
    freeSpinReelStrips: [
      ['A', 'B', 'S'],
      ['A', 'B', 'S'],
      ['A', 'B', 'S'],
    ],
    paylines: [{ id: 'L1', rows: [0, 0, 0] }],
    paytable: [
      { symbolId: 'A', count: 3, awardCredits: 10 },
      { symbolId: 'B', count: 3, awardCredits: 5 },
    ],
    bonus: {
      schemaVersion: '1.1.0',
      enabled: true,
      triggerSymbolId: 'S',
      triggerEvaluation: 'anywhere',
      minimumCount: 3,
      awards: [{ count: 3, freeSpins: 2 }],
      freeSpinMultiplier: 1,
      retriggerEnabled: true,
      retriggerAwards: [{ count: 3, freeSpins: 1 }],
      maximumFeatureSpins: 10,
      maximumRetriggers: 2,
      scatterPaysCredits: false,
      useAlternateReelStrips: false,
      useAlternatePaytable: false,
    },
    rules: {
      schemaVersion: '1.0.0',
      wild: {
        symbolId: 'W',
        enabled: true,
        substitutesFor: ['A', 'B'],
        substitutesForWild: true,
        substitutesForScatter: false,
        hasOwnLinePay: false,
        multiplier: 1,
        allWildCombinationRule: 'no-pay',
      },
      lineAwardRules: {
        direction: 'left-to-right',
        activePaylines: 1,
        lineBetCredits: 1,
        totalBetCredits: 1,
        awardScaling: 'award-credits-per-line-bet',
        matchRule: 'consecutive-from-leftmost-reel',
        winSelection: 'highest-award-per-payline',
        multiplePaylinesAccumulate: true,
        nestedAwardsAccumulate: false,
        scatterBreaksLineMatch: true,
      },
      scatter: {
        symbolId: 'S',
        enabled: true,
        evaluation: 'anywhere',
        countMode: 'visible-symbols',
        maximumCountMode: 'one-visible-scatter-per-reel',
        substitutesOnLines: false,
        wildSubstitutesForScatter: false,
        scatterSubstitutesForRegular: false,
        directCreditPaysEnabled: false,
        triggersFeature: true,
      },
    },
  };
}
